spring:
  datasource:
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_jpa?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
